const DataDesktop14 = [
  {
    Id: 1,
    Head: "TECHNOLOGY ANNUAL FAIR",
    // Poster: "../../",
    Data: "Lorem ipsum dolor sit amet consectetur. Orci nam fringilla at nunc id lorem. Sed orci nulla pulvinar libero pharetra sollicitudin nulla. Faucibus in tristique ac pharetra viverra tortor. Eget velit eu sagittis aliquam ac sit sed turpis libero. Cursus elementum ultricies id aliquam netus rutrum at duis scelerisque. Neque nibh lectus quisque pulvinar at varius lorem. Proin morbi eget risus nibh sit diam hendrerit vulputate sed. Suspendisse cras nisi est vitae praesent et aliquet facilisis accumsan. Arcu mi mauris leo aliquet dictumst. Risus sem ut condimentum massa ullamcorper iaculis arcu arcu. Mus varius dignissim eros justo Id elit eget magna commodo arcu sem. Tempor sed blandit eget curabitur id sem facilisi sit nulla. Parturient cursus diam dolor velit pulvinar gravida convallis. In enim ornare lacus viverra vulputate. Eu ut nulla mauris et. Gravida feugiat nisi quam ipsum sagittis placerat sodales id. Cursus vitae mauris suspendisse metus suspendisse egestas est rhoncus tortor. Elit commodo mattis sed dolor orci imperdiet. Quisque et facilisis hac duis sit lorem consequat eu. Eu massa ultrices scelerisque et. Convallis eget eget congue id ullamcorper faucibus urna. Non leo volutpat mauris facilisis. Ac quam commodo faucibus morbi. Mi interdum vitae lacus volutpat. Malesuada aenean urna facilisis felis sociis elementum. Cras platea maecenas dictumst sem pellentesque phasellus blandit. Ut id elementum amet fermentum tincidunt sit blandit. Ultrices consectetur leo pellentesque sit euismod adipiscing elementum. Pellentesque eu nam varius in parturient vehicula. Ut tristique sed ac aenean. Tellus tortor accumsan faucibus donec commodo. Eu eget at accumsan aliquet commodo sit volutpat diam nec. Dictumst vestibulum eget purus consectetur. Lobortis porttitor fames massa imperdiet vitae erat sit congue. Tellus ipsum neque duis ipsum elementum odio gravida. Amet pellentesque praesent orci euismod lacus sed placerat. Nisi malesuada commodo amet eu sit. Enim iaculis bibendum sem elementum sed elementum. Amet et pellentesque euismod euismod interdum. Quis donec consequat sit ultricies. Quam aliquam turpis vitae in purus vulputate pellentesque tempus vitae. Vitae ultrices mauris pellentesque orci quis hac sed. Sit tortor auctor tincidunt quis et odio fames vulputate. Ut volutpat rhoncus et netus fermentum amet sit enim. Dignissim eget vestibulum turpis lacinia. Quam urna et integer at arcu duis a.",
  },
];
export { DataDesktop14 };
